#!/bin/bash

cat > $SILVA_TO_SOURCE_IN << 'SETUP_BASH'
#!/bin/bash

if [ -z "$SILVA_BASH_SETUP_HISTORY" ]; then
    # making history!!!1111
    # Eternal bash history.
    # ---------------------
    # Undocumented feature which sets the size to "unlimited".
    # http://stackoverflow.com/questions/9457233/unlimited-bash-history
    export HISTFILESIZE=
    export HISTSIZE=
    export HISTTIMEFORMAT="[%F %T] "
    # Change the file location because certain bash sessions truncate .bash_history file upon close.
    # http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
    export HISTFILE=~/.bash_eternal_history
    export HISTCONTROL=ignoredups:erasedups
    # Force prompt to write history after every command.
    # http://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows
    shopt -s histappend
    export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
    export SILVA_BASH_SETUP_HISTORY=1
fi

SETUP_BASH